import Head from 'next/head';
import Container from '../layout/Container';
import NavBar from '../layout/NavBar';
import HeroWithDrop from '../components/HeroWithDrop';

export default function Home( { data } ) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    <Container>
      <NavBar />
      <HeroWithDrop data={data}/>
    </Container>

    </>
  )
}

export async function getStaticProps () {

  const res = await fetch('http://localhost:3000/api/getData');
  const data = await res.json()
 
  return {
    props: {
      data
    }, 
  }
}